// frontend/src/components/SearchBar.tsx
import { useEffect, useRef } from 'react'

interface SearchBarProps {
  value: string
  onChange: (value: string) => void
  matchCase: boolean
  matchWholeWord: boolean
  matchPath: boolean
  useRegex: boolean
  appAndFolderOnly: boolean
  showHistory: boolean
  onToggleHistory: () => void
  onMatchCaseChange: (value: boolean) => void
  onMatchWholeWordChange: (value: boolean) => void
  onMatchPathChange: (value: boolean) => void
  onUseRegexChange: (value: boolean) => void
  onAppAndFolderOnlyChange: (value: boolean) => void
}

function SearchBar({
  value,
  onChange,
  matchCase,
  matchWholeWord,
  matchPath,
  useRegex,
  appAndFolderOnly,
  showHistory,
  onToggleHistory,
  onMatchCaseChange,
  onMatchWholeWordChange,
  onMatchPathChange,
  onUseRegexChange,
  onAppAndFolderOnlyChange
}: SearchBarProps) {
  const inputRef = useRef<HTMLInputElement>(null)

  useEffect(() => {
    inputRef.current?.focus()
  }, [])

  return (
    <div className="search-bar">
      <div className="search-input-wrapper">
        <input
          ref={inputRef}
          type="text"
          className="search-input"
          value={value}
          onChange={(e) => onChange(e.target.value)}
          placeholder="搜索应用、文件夹和文件..."
          autoFocus
        />
        <button
          className={`history-toggle ${showHistory ? 'active' : ''}`}
          onClick={onToggleHistory}
          title="切换搜索历史 (Ctrl+↑)"
        >
          <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
            <path d="M12 8v4l3 3" />
            <circle cx="12" cy="12" r="10" />
          </svg>
        </button>
      </div>

      <div className="search-options">
        <button
          className={`option-btn-primary ${appAndFolderOnly ? 'active' : ''}`}
          onClick={() => onAppAndFolderOnlyChange(!appAndFolderOnly)}
          title="仅搜索应用和文件夹"
        >
          <span>{appAndFolderOnly ? '☑' : '☐'}</span>
          <span>仅搜索应用和文件夹</span>
        </button>

        <div className="option-divider" />

        <button
          className={`option-btn ${matchCase ? 'active' : ''}`}
          onClick={() => onMatchCaseChange(!matchCase)}
          title="区分大小写"
        >
          Aa
        </button>
        <button
          className={`option-btn ${matchWholeWord ? 'active' : ''}`}
          onClick={() => onMatchWholeWordChange(!matchWholeWord)}
          title="全词匹配"
        >
          W
        </button>
        <button
          className={`option-btn ${matchPath ? 'active' : ''}`}
          onClick={() => onMatchPathChange(!matchPath)}
          title="匹配路径"
        >
          P
        </button>
        <button
          className={`option-btn ${useRegex ? 'active' : ''}`}
          onClick={() => onUseRegexChange(!useRegex)}
          title="使用正则表达式"
        >
          .*
        </button>
      </div>
    </div>
  )
}

export default SearchBar

// frontend/src/components/SearchBar.vue
<script lang="ts" setup>
import { ref, computed, onMounted } from 'vue'

const props = defineProps<{
  modelValue: string
  matchCase: boolean
  matchWholeWord: boolean
  useRegex: boolean
  showHistory: boolean
}>()

const emit = defineEmits<{
  'update:modelValue': [value: string]
  'update:matchCase': [value: boolean]
  'update:matchWholeWord': [value: boolean]
  'update:useRegex': [value: boolean]
  'toggleHistory': []
}>()

const inputRef = ref<HTMLInputElement | null>(null)

function updateValue(e: Event) {
  const target = e.target as HTMLInputElement
  emit('update:modelValue', target.value)
}

function toggleMatchCase() {
  emit('update:matchCase', !props.matchCase)
}

function toggleMatchWholeWord() {
  emit('update:matchWholeWord', !props.matchWholeWord)
}

function toggleUseRegex() {
  emit('update:useRegex', !props.useRegex)
}

function focusInput() {
  inputRef.value?.focus()
}

// Auto-focus on mount
onMounted(() => {
  focusInput()
})
</script>

<template>
  <div class="search-bar">
    <div class="search-input-wrapper">
      <input
        ref="inputRef"
        type="text"
        class="search-input"
        :value="modelValue"
        @input="updateValue"
        placeholder="Search files..."
        autofocus
      />
      <button
        class="history-toggle"
        :class="{ active: showHistory }"
        @click="emit('toggleHistory')"
        title="Toggle search history (Ctrl+Up)"
      >
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <path d="M12 8v4l3 3"/>
          <circle cx="12" cy="12" r="10"/>
        </svg>
      </button>
    </div>
    
    <div class="search-options">
      <button
        class="option-btn"
        :class="{ active: matchCase }"
        @click="toggleMatchCase"
        title="Match case"
      >
        Aa
      </button>
      <button
        class="option-btn"
        :class="{ active: matchWholeWord }"
        @click="toggleMatchWholeWord"
        title="Match whole word"
      >
        W
      </button>
      <button
        class="option-btn"
        :class="{ active: useRegex }"
        @click="toggleUseRegex"
        title="Use regular expression"
      >
        .*
      </button>
    </div>
  </div>
</template>

<style scoped>
.search-bar {
  display: flex;
  flex-direction: column;
  padding: 8px;
  background: var(--bg-secondary);
  border-bottom: 1px solid var(--border);
}

.search-input-wrapper {
  display: flex;
  align-items: center;
  gap: 8px;
}

.search-input {
  flex: 1;
  padding: 10px 12px;
  font-size: 16px;
  border: none;
  border-radius: 4px;
  background: var(--bg-primary);
  color: var(--text-primary);
  outline: none;
}

.search-input::placeholder {
  color: var(--text-secondary);
}

.search-input:focus {
  box-shadow: 0 0 0 2px var(--accent);
}

.history-toggle {
  padding: 8px;
  border: none;
  border-radius: 4px;
  background: transparent;
  color: var(--text-secondary);
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all 0.2s;
}

.history-toggle:hover {
  background: var(--bg-hover);
  color: var(--text-primary);
}

.history-toggle.active {
  background: var(--accent);
  color: white;
}

.search-options {
  display: flex;
  gap: 4px;
  margin-top: 8px;
}

.option-btn {
  padding: 4px 8px;
  font-size: 12px;
  border: 1px solid var(--border);
  border-radius: 4px;
  background: transparent;
  color: var(--text-secondary);
  cursor: pointer;
  transition: all 0.2s;
}

.option-btn:hover {
  background: var(--bg-hover);
  color: var(--text-primary);
}

.option-btn.active {
  background: var(--accent);
  color: white;
  border-color: var(--accent);
}
</style>
