// frontend/src/App.tsx
import { useState, useEffect, useCallback, useRef, useMemo } from 'react'
import SearchBar from './components/SearchBar'
import ResultList, { ResultGroup } from './components/ResultList'
import HistoryPanel from './components/HistoryPanel'
import { Search, GetHistory, ShowWindow, HideWindow, OpenFile } from '../wailsjs/go/main/App'
import './App.css'

interface SearchResult {
  fileName: string
  fullPath: string
  isFolder: boolean
  size: number
  dateModified: string
}

// 判断是否为 App / 可执行程序
const APP_EXTENSIONS = ['exe', 'msi', 'app', 'lnk', 'appx', 'dmg', 'pkg']
function isAppFile(fileName: string): boolean {
  const ext = fileName.split('.').pop()?.toLowerCase() || ''
  return APP_EXTENSIONS.includes(ext)
}

function App() {
  const [query, setQuery] = useState('')
  const [results, setResults] = useState<SearchResult[]>([])
  const [history, setHistory] = useState<string[]>([])
  const [showHistory, setShowHistory] = useState(false)
  const [selectedIndex, setSelectedIndex] = useState(-1)
  const [isLoading, setIsLoading] = useState(false)
  const [errorMessage, setErrorMessage] = useState('')

  // Search options
  const [matchCase, setMatchCase] = useState(false)
  const [matchWholeWord, setMatchWholeWord] = useState(false)
  const [matchPath, setMatchPath] = useState(false)
  const [useRegex, setUseRegex] = useState(false)
  const [appAndFolderOnly, setAppAndFolderOnly] = useState(true)

  const searchTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  // Perform search
  const performSearch = useCallback(async () => {
    if (!query.trim()) {
      setResults([])
      return
    }

    setIsLoading(true)
    setErrorMessage('')

    try {
      const opts = {
        matchCase,
        matchWholeWord,
        matchPath,
        useRegex,
        appAndFolderOnly,
        maxResults: 100
      }

      const searchResults = await Search(query, opts)
      setResults(searchResults || [])
      setSelectedIndex(searchResults && searchResults.length > 0 ? 0 : -1)
      setShowHistory(false)
    } catch (err: any) {
      setErrorMessage(err.message || 'Search failed')
      setResults([])
    } finally {
      setIsLoading(false)
    }
  }, [query, matchCase, matchWholeWord, matchPath, useRegex, appAndFolderOnly])

  // 按 App / 文件夹 / 文件 分组
  const groupedResults = useMemo<ResultGroup[]>(() => {
    const apps: SearchResult[] = []
    const folders: SearchResult[] = []
    const files: SearchResult[] = []

    for (const r of results) {
      if (r.isFolder) {
        folders.push(r)
      } else if (isAppFile(r.fileName)) {
        apps.push(r)
      } else {
        files.push(r)
      }
    }

    const groups: ResultGroup[] = []
    if (apps.length) groups.push({ title: '应用', icon: '🚀', items: apps })
    if (folders.length) groups.push({ title: '文件夹', icon: '📁', items: folders })
    if (files.length) groups.push({ title: '文件', icon: '📄', items: files })
    return groups
  }, [results])

  // 扁平化的结果列表，用于键盘导航
  const flatResults = useMemo(
    () => groupedResults.flatMap(g => g.items),
    [groupedResults]
  )

  // Debounced search
  useEffect(() => {
    if (searchTimerRef.current) clearTimeout(searchTimerRef.current)
    searchTimerRef.current = setTimeout(performSearch, 300)
    return () => {
      if (searchTimerRef.current) clearTimeout(searchTimerRef.current)
    }
  }, [query, performSearch])

  // Load history
  const loadHistory = useCallback(async () => {
    try {
      const hist = await GetHistory()
      setHistory(hist || [])
    } catch (e) {
      console.error('Failed to load history:', e)
    }
  }, [])

  // Handle history item click
  const selectHistoryItem = useCallback((item: string) => {
    setQuery(item)
    setShowHistory(false)
    setTimeout(() => performSearch(), 0)
  }, [performSearch])

  // Handle result selection
  const selectResult = useCallback(async (result: SearchResult) => {
    try {
      await OpenFile(result.fullPath)
    } catch (e) {
      console.error('Failed to open file:', e)
    }
  }, [])

  // Handle keyboard navigation
  const handleKeyDown = useCallback((e: KeyboardEvent) => {
    if (e.key === 'Escape') {
      HideWindow()
      return
    }

    // Show history on Ctrl+Up（需先判断，避免被 ArrowUp 拦截）
    if (e.key === 'ArrowUp' && e.ctrlKey) {
      e.preventDefault()
      loadHistory()
      setShowHistory(prev => !prev)
      return
    }

    if (e.key === 'ArrowDown') {
      e.preventDefault()
      setSelectedIndex(prev => Math.min(prev + 1, flatResults.length - 1))
      return
    }

    if (e.key === 'ArrowUp') {
      e.preventDefault()
      setSelectedIndex(prev => Math.max(prev - 1, 0))
      return
    }

    if (e.key === 'Enter' && selectedIndex >= 0) {
      e.preventDefault()
      const result = flatResults[selectedIndex]
      if (result) {
        selectResult(result)
      }
      return
    }
  }, [flatResults, selectedIndex, selectResult, loadHistory])

  // Window blur handler
  const handleWindowBlur = useCallback(() => {
    HideWindow()
  }, [])

  // Lifecycle
  useEffect(() => {
    loadHistory()
    window.addEventListener('keydown', handleKeyDown)
    window.addEventListener('blur', handleWindowBlur)
    ShowWindow()

    return () => {
      window.removeEventListener('keydown', handleKeyDown)
      window.removeEventListener('blur', handleWindowBlur)
    }
  }, [loadHistory, handleKeyDown, handleWindowBlur])

  return (
    <div className={`app-container ${isLoading ? 'is-loading' : ''}`}>
      <div className="main-panel">
        <SearchBar
          value={query}
          onChange={setQuery}
          matchCase={matchCase}
          matchWholeWord={matchWholeWord}
          matchPath={matchPath}
          useRegex={useRegex}
          appAndFolderOnly={appAndFolderOnly}
          showHistory={showHistory}
          onToggleHistory={() => setShowHistory(prev => !prev)}
          onMatchCaseChange={setMatchCase}
          onMatchWholeWordChange={setMatchWholeWord}
          onMatchPathChange={setMatchPath}
          onUseRegexChange={setUseRegex}
          onAppAndFolderOnlyChange={setAppAndFolderOnly}
        />

        {showHistory && history.length > 0 && (
          <HistoryPanel items={history} onSelect={selectHistoryItem} />
        )}

        {errorMessage && (
          <div className="error-message">{errorMessage}</div>
        )}

        {!errorMessage && flatResults.length > 0 && (
          <ResultList
            groups={groupedResults}
            selectedIndex={selectedIndex}
            onSelect={selectResult}
          />
        )}

        {!errorMessage && query && !isLoading && flatResults.length === 0 && (
          <div className="empty-state">未找到相关结果</div>
        )}
      </div>
    </div>
  )
}

export default App

// frontend/src/App.vue
<script lang="ts" setup>
import { ref, onMounted, onUnmounted, watch, nextTick } from 'vue'
import SearchBar from './components/SearchBar.vue'
import ResultList from './components/ResultList.vue'
import HistoryPanel from './components/HistoryPanel.vue'

import { Search, GetHistory, ShowWindow, HideWindow, OpenFile } from '../wailsjs/go/main/App'

// Types
interface SearchResult {
  fileName: string
  fullPath: string
  isFolder: boolean
  size: number
  dateModified: string
}

// State
const query = ref('')
const results = ref<SearchResult[]>([])
const history = ref<string[]>([])
const showHistory = ref(false)
const selectedIndex = ref(-1)
const isLoading = ref(false)
const errorMessage = ref('')

// Search options
const matchCase = ref(false)
const matchWholeWord = ref(false)
const useRegex = ref(false)

// Debounce timer
let searchTimer: ReturnType<typeof setTimeout> | null = null

// Perform search
async function performSearch() {
  if (!query.value.trim()) {
    results.value = []
    return
  }

  isLoading.value = true
  errorMessage.value = ''

  try {
    const opts = {
      matchCase: matchCase.value,
      matchWholeWord: matchWholeWord.value,
      useRegex: useRegex.value,
      maxResults: 100
    }
    
    const searchResults = await Search(query.value, opts)
    results.value = searchResults || []
    selectedIndex.value = results.value.length > 0 ? 0 : -1
    showHistory.value = false
  } catch (err: any) {
    errorMessage.value = err.message || 'Search failed'
    results.value = []
  } finally {
    isLoading.value = false
  }
}

// Watch query with debounce
watch(query, () => {
  if (searchTimer) clearTimeout(searchTimer)
  searchTimer = setTimeout(performSearch, 300)
})

// Load history
async function loadHistory() {
  try {
    history.value = await GetHistory() || []
  } catch (e) {
    console.error('Failed to load history:', e)
  }
}

// Handle history item click
function selectHistoryItem(item: string) {
  query.value = item
  showHistory.value = false
  nextTick(() => performSearch())
}

// Handle result selection - opens the file
async function selectResult(result: SearchResult) {
  try {
    await OpenFile(result.fullPath)
  } catch (e) {
    console.error('Failed to open file:', e)
  }
}

// Handle keyboard navigation
function handleKeyDown(e: KeyboardEvent) {
  if (e.key === 'Escape') {
    HideWindow()
    return
  }

  if (e.key === 'ArrowDown') {
    e.preventDefault()
    if (selectedIndex.value < results.value.length - 1) {
      selectedIndex.value++
    }
    return
  }

  if (e.key === 'ArrowUp') {
    e.preventDefault()
    if (selectedIndex.value > 0) {
      selectedIndex.value--
    }
    return
  }

  if (e.key === 'Enter' && selectedIndex.value >= 0) {
    e.preventDefault()
    const result = results.value[selectedIndex.value]
    if (result) {
      selectResult(result)
    }
    return
  }

  // Show history on Ctrl+Up
  if (e.key === 'ArrowUp' && e.ctrlKey) {
    e.preventDefault()
    loadHistory()
    showHistory.value = !showHistory.value
    return
  }
}

// Window focus handling
function handleWindowBlur() {
  HideWindow()
}

// Lifecycle
onMounted(() => {
  loadHistory()
  window.addEventListener('keydown', handleKeyDown)
  window.addEventListener('blur', handleWindowBlur)
  ShowWindow()
})

onUnmounted(() => {
  window.removeEventListener('keydown', handleKeyDown)
  window.removeEventListener('blur', handleWindowBlur)
})
</script>

<template>
  <div class="app-container" :class="{ 'is-loading': isLoading }">
    <SearchBar
      v-model="query"
      :match-case="matchCase"
      :match-whole-word="matchWholeWord"
      :use-regex="useRegex"
      :show-history="showHistory"
      @toggle-history="showHistory = !showHistory"
      @update:match-case="matchCase = $event"
      @update:match-whole-word="matchWholeWord = $event"
      @update:use-regex="useRegex = $event"
    />
    
    <HistoryPanel
      v-if="showHistory && history.length > 0"
      :items="history"
      @select="selectHistoryItem"
    />
    
    <div v-if="errorMessage" class="error-message">
      {{ errorMessage }}
    </div>
    
    <ResultList
      v-else-if="results.length > 0"
      :results="results"
      :selected-index="selectedIndex"
      @select="selectResult"
    />
    
    <div v-else-if="query && !isLoading" class="empty-state">
      No results found
    </div>
  </div>
</template>

<style>
:root {
  --bg-primary: #1e1e1e;
  --bg-secondary: #2d2d2d;
  --bg-hover: #3d3d3d;
  --text-primary: #e0e0e0;
  --text-secondary: #a0a0a0;
  --accent: #0078d4;
  --accent-hover: #1a86d9;
  --border: #404040;
  --error: #f44336;
}

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

html, body {
  font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
  font-size: 14px;
  background: transparent;
  overflow: hidden;
}

.app-container {
  width: 100%;
  height: 100vh;
  background: var(--bg-primary);
  border-radius: 8px;
  display: flex;
  flex-direction: column;
  overflow: hidden;
}

.error-message {
  padding: 16px;
  color: var(--error);
  text-align: center;
}

.empty-state {
  padding: 32px;
  color: var(--text-secondary);
  text-align: center;
}

.is-loading .app-container::after {
  content: '';
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  height: 2px;
  background: var(--accent);
  animation: loading 1s ease-in-out infinite;
}

@keyframes loading {
  0% { transform: translateX(-100%); }
  100% { transform: translateX(100%); }
}
</style>
